# -*- coding: utf-8 -*-
"""train_xlm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHWH2358XW0ssqzCRKVyUQ_G_q5H3inA
"""

import torch
print("cuda", torch.cuda.is_available(), torch.cuda.get_device_name(0) if torch.cuda.is_available() else None)

import json
from pathlib import Path
from datasets import Dataset
from transformers import AutoTokenizer

CATEGORIES=["sports", "politics", "economy", "culture", "world"]
label2id = {name: i for i, name in enumerate(CATEGORIES)}
id2label = {i: name for name, i in label2id.items()}

def load_jsonl(path):
    rows = []
    with Path(path).open(encoding="utf-8") as f:
        for line in f:
            line=line.strip()
            if not line: continue
            row=json.loads(line)
            rows.append({"text": row["text"], "label": label2id[row["label"]]})
    return Dataset.from_list(rows)

train=load_jsonl("aznews-xlm/data/splits/train.jsonl")
val=load_jsonl("aznews-xlm/data/splits/val.jsonl")
test=load_jsonl("aznews-xlm/data/splits/test.jsonl")
print(train, val, test)
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
def tokenize(batch): return tokenizer(batch["text"], truncation=True, max_length=256)

train=train.map(tokenize, batched=True)
val=val.map(tokenize, batched=True)
test=test.map(tokenize, batched=True)

print(train[0]["label"], train[0]["input_ids"][:20])
print(tokenizer.decode(train[0]["input_ids"][:20]))

import numpy as np
from sklearn.metrics import accuracy_score, classification_report, f1_score
from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments

train=train.remove_columns(["text"])
val=val.remove_columns(["text"])
test=test.remove_columns(["text"])

model = AutoModelForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

def compute_metrics(eval_pred):
    logits,labels = eval_pred
    predicts=np.argmax(logits,axis=-1)
    return {
        "accuracy": accuracy_score(labels,predicts),
        "macro_f1": f1_score(labels,predicts,average="macro")
    }

args = TrainingArguments(
    output_dir="aznews-xlm/models/xlm-r",
    num_train_epochs=4,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    fp16=True,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train,
    eval_dataset=val,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()
print("val (best checkpoint)", trainer.evaluate())

test_out = trainer.predict(test)
test_preds = np.argmax(test_out.predictions, axis=-1)
print(classification_report(test_out.label_ids, test_preds, target_names=CATEGORIES))

print(classification_report(test_out.label_ids, test_preds, target_names=CATEGORIES, digits=3))